config/routes.rb
Rails.application.routes.draw do
  root 'home#index'

  devise_for :users

  resources :categories do
    resources :movements
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories.rb
class Categories < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :category_movements, foreign_key: :category_id

  has_one_attached :icon

  validates :name, presence: true
  validates :icon, presence: true
end

app/models/category_movement.rb
class CategoryMovement < ApplicationRecord
  belongs_to :categories, class_name: 'Categories', foreign_key: :category_id
  belongs_to :movements, class_name: 'Movement', foreign_key: :movements_id
end

app/models/movement.rb
class Movement < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: :author_id
  has_many :category_movements, foreign_key: :movements_id

  validates :name, presence: true
  validates :amount, numericality: { grater_than: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :categories, foreign_key: :author_id, class_name: 'Categories'
  has_many :movements, foreign_key: :author_id, class_name: 'Movement'

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(_resource)
    categories_path
  end

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name])
  end

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |user|
      user.permit(:name)
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :authenticate_user!

  def index
    @categories = current_user.categories.includes(icon_attachment: :blob)

    @category_totals = calc_total_amount(@categories)
  end

  def new
    @category = Categories.new
  end

  def create
    category = current_user.categories.new(category_params)
    if category.save
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:categories).permit(:name, :icon)
  end

  def calc_total_amount(categories)
    totals = {}
    categories.each do |category|
      total_amount = category.category_movements.includes(:movements).sum { |movement| movement.movements.amount }
      totals[category.name] = total_amount
    end
    totals
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/movements_controller.rb
class MovementsController < ApplicationController
  before_action :authenticate_user!

  def index
    @category = Categories.find(params[:category_id])
    @movements = CategoryMovement.where(category_id: params[:category_id]).includes(:movements).order(created_at: :desc)
  end

  def new
    @categories = Categories.all
    @movement = Movement.new
  end

  def create
    name = params[:movement][:name]
    amount = params[:movement][:amount]
    category = Categories.find(params[:movement][:category])
    @movement = Movement.new(author_id: current_user.id, name:, amount:)

    if @movement.save
      CategoryMovement.create(category_id: category.id, movements_id: @movement.id)

      redirect_to category_movements_path(category.id)
    else
      redirect_to new_category_movement_path(params[:category_id])
    end
  end

  private

  def movement_params
    params.require(:movement).permit(:name, :amount, :category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def menu
    nav = ''
    if controller_name == 'categories' && action_name == 'index'
      nav << "<li>
                #{link_to 'GeldSpar', categories_path, class: 'no-underline'}
              </li>"
      nav << "<li>
                <span class='family-head'>HOME</span>
              </li>"
    end
    if controller_name == 'categories' && action_name == 'new'
      nav << "<li class='material-symbols-outlined'>
                #{link_to 'arrow_back', categories_path, class: 'no-underline'}
              </li>"
      nav << "<li>
                <span class='family-head'>ADD CATEGORY</span>
              </li>"
    end
    menu_links(nav)
  end

  def menu_links(nav)
    if controller_name == 'movements' && action_name == 'index'
      nav << "<li class='material-symbols-outlined'>
                #{link_to 'arrow_back', categories_path, class: 'no-underline'}
              </li>"
      nav << "<li>
                <span class='family-head'>MOVEMENTS</span>
              </li>"
    end
    if controller_name == 'movements' && action_name == 'new'
      nav << "<li class='material-symbols-outlined'>
                #{link_to 'arrow_back', category_movements_path(params[:category_id]), class: 'no-underline'}
              </li>"
      nav << "<li>
                <span class='family-head'>ADD MOVEMENT</span>
              </li>"
    end
    nav << "<li>
              #{button_to 'Sign Out', destroy_user_session_path, method: :delete, class: 'link-seeming font-nav'}
            </li>"
    nav.html_safe
  end

  def category_total(category)
    category.category_movements.includes(:movements).sum { |movement| movement.movements.amount }
  end
end

app/views/categories/index.html.erb
<section class="content-wrap">

  <%= render partial: 'partials/menu' %>

  <div class="d-flex-col category-container a-center">
    <%= render partial: 'partials/category_card', collection: @categories, as: :category %>
  </div>

  <div class="d-flex j-center green-container">
    <%= link_to 'Add new category', new_category_path, class: "d-flex btn-green family-general" %>
  </div>

</section>

app/views/categories/new.html.erb
<%= render partial: 'partials/menu' %>
<%= form_with(model: @category, url: categories_path(@category)) do |f| %>

  <div class="d-flex-col field a-center">
    <%= f.text_field :name, required: true, placeholder: "Category name", class: "form-input family-general" %>
    
    <div class="file-container">
      <%= f.label :icon, class: "d-flex gap" do %>
        <span class="d-flex j-center fancy-file-button family-general">Select file</span>
        <span class="d-flex fancy-file-name family-general color-font-general">Any file selected</span>
      <% end %>
      <%= f.file_field :icon, required: true, class: "fancy-file" %>
    </div>
    
    <%= f.submit "Save category", class: "btn-submit" %>
  </div>

<% end %>

<script>
  const files = document.querySelectorAll('.fancy-file')
  Array.from(files).forEach(
    f => {
      f.addEventListener('change', e => {
        const span = document.querySelector('.fancy-file-name')
        if(f.files.length == 0) {
          span.innerHTML = "Any file selected"
        }else {
          span.innerHTML = f.files[0].name
        }
      })
    }
  )
</script>

app/views/category_movements/index.html.erb
categoryMovemens#index

app/views/home/index.html.erb
<section class="home-container">
  <div class="d-flex j-center ">
    <h1 class="d-flex font-title">GeldSpar</h1>
  </div>
  <div class="d-flex-col m0 a-center j-center">
    <%= link_to 'LOG IN', new_user_session_path, class: 'btn-seeming d-flex btn-login' %>
    <%= link_to 'SIGN UP', new_user_registration_path, class: 'btn-seeming d-flex' %>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@24,400,0,0" />

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "container", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "medias", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main>
      <div class="page-container">
        <%= yield %>    
      </div>
    </main>
  </body>
</html>

app/views/movements/index.html.erb
<section class="content-wrap">
  <%= render partial: 'partials/menu' %>

  <div class="d-flex j-center">
    <div class="grid-container-2 movement-head j-center color-font-general">
      <span><%= image_tag @category.icon %></span>
      <div class="d-flex-col family-head ">
        <span><%= @category.name %></span>
        Total amount: $<%= number_with_precision(category_total(@category), precision: 2) %>
      </div>
    </div>
  </div>

  <div class="d-flex-col category-container a-center">
    <%= render partial: 'partials/movement_card', collection: @movements, as: :movement %>
  </div>

  <div class="d-flex j-center green-container">
    <%= link_to 'Add a new movement', new_category_movement_path(@category.id), class: "d-flex btn-green family-general" %>
  </div>
</section>

app/views/movements/new.html.erb
<%= render partial: 'partials/menu' %>

<%= form_with(model: @movement, url: category_movements_path(params[:category_id])) do |f| %>

  <div class="d-flex-col field a-center">
    <%= f.text_field :name, required: true, placeholder: "Movement name", class: "form-input family-general" %>

    <%= f.text_field :amount, :required => true, type: 'number', step: '0.01', placeholder: "Amount", class: "form-input family-general" %>

    <%= f.collection_select :category, @categories, :id, :name %>

    <%= f.submit "Save movement", class: "btn-submit" %>
  </div>

<% end %>

app/views/partials/_category_card.html.erb
<%= link_to category_movements_path(category.id), class: "family-general no-underline color-font-general grid-container category-card" do %>
    <%= image_tag category.icon %>
    <div><%= category.name %> </div>
    <span class="d-flex j-end family-head">$<%= number_with_precision(@category_totals[category.name], precision: 2) %></span>
<% end %>

app/views/partials/_menu.html.erb
<nav>
  <ul class="d-flex m0 ul-nav">
    <%= menu %>
  </ul>
</nav>

app/views/partials/_movement_card.html.erb
<div class="movement-card grid-container-2 family-general color-font-general">
  <div class="d-flex-col">
    <span><%= movement.movements.name %></span>
    <span><%= movement.movements.created_at.strftime("%d %b %Y") %></span>
  </div>
  <div class="d-flex j-end">
    <span class="family-head">$<%= number_with_precision(movement.movements.amount, precision: 2) %></span>
  </div>
</div>

app/views/users/index.html.erb
user#index